repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    language: system
    entry: isort --check
    files: '\.py$'
  - id: black
    name: Black formatter
    language: system
    entry: black --check
    files: '\.py$'
  - id: flake8
    name: Flake8
    language: system
    entry: flake8
    files: '\.py$'
