# install: mamba env create -f environment.yml
# update: mamba env update -f environment.yml

name: porcupine-notebooks
channels:
  - conda-forge
dependencies:
  - notebook
  - pandas
  - geopandas
  - rasterio
  - rioxarray
  - ipykernel
  - matplotlib 
  - boto3
  - xarray
  - dask
  - pystac
  - shapely
  - pystac-client
  - s3fs
  - folium
  - planetary-computer
  - odc-stac
