name: Python Test Suite

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Test with pytest
        run: |
          python -m pip install -e .
          python -m pip install pytest
          $CONDA/bin/pytest -vvs medaprep/tests
